// pages/resume.vue
<template>
    <main class="max-w-[820px] mx-4 md:mx-auto space-y-4">
        <ResumeHeader name="Lukas Grimm" role="Software Engineer from Berlin, Germany" />
        <div class="flex flex-col md:flex-row space-y-4 md:space-x-6 md:space-y-0">
            <div class="flex flex-col md:min-w-[240px] md:w-1/3 md:max-w-[360px] space-y-4">
                <ResumeSection title="Biography">
                    <ResumeBiography :biography="biography!" />
                </ResumeSection>
                <ResumeSection title="Strengths">
                    <ul class="flex flex-col space-y-2">
                        <li v-for="strength in resume?.strengths">
                            <ResumeStrengthItem :strength="strength" />
                        </li>
                    </ul>
                </ResumeSection>
            </div>
            <div class="flex flex-col space-y-4">
                <ResumeSection title="Experience">
                    <ResumeExperienceList :experiences="resume?.experience || []" />
                </ResumeSection>
                <ResumeSection title="Education">
                    <ResumeEducationList :educations="resume?.education || []" />
                </ResumeSection>
                <ResumeSection title="Skills">
                    <ul class="grid grid-cols-3 gap-4">
                        <li v-for="skill in resume?.skills">
                            <ResumeSkillItem :skill="skill" />
                        </li>
                    </ul>
                </ResumeSection>
            </div>
        </div>
    </main>
</template>

<script setup lang="ts">
    import type { BiographyModel, EducationItemModel, ExperienceItemModel, SkillItemModel, StrengthItemModel } from '~/components/resume/models';

    type ResumeModel = {
        experience: ExperienceItemModel[];
        education: EducationItemModel[];
        skills: SkillItemModel[];
        strengths: StrengthItemModel[];
    }

    const { data: resume } = await useAsyncData('resume', () => queryContent<ResumeModel>('resume').findOne().then((data) => ({
        ...data,
    })));
    
    if (resume.value) {
        resume.value.experience = resume.value?.experience?.map((experience) => ({
            ...experience,
            start: new Date(experience.start),
            end: experience.end ? new Date(experience.end) : undefined
        })) || [];

        resume.value.education = resume.value?.education?.map((education) => ({
            ...education,
            start: new Date(education.start),
            end: education.end ? new Date(education.end) : undefined
        })) || [];

        console.log(resume.value)
    }

    const { data: biography } = await useAsyncData('biography', () => queryContent<BiographyModel>('biography').findOne())

    useHead({
        title: `${biography.value?.name} - ${biography.value?.role}`,
        meta: [
            { name: 'description', content: biography.value?.about }
        ],
    });
</script>

// app/resume/page.tsx
import { loadJsonFile } from '@/lib/load-file';
import type { Resume } from '@/models/resume';
import { Metadata } from 'next';
import { Biography } from './biography';
import { EducationList } from './education-list';
import { ExperienceList } from './experience-list';
import { ResumeSection } from './resume-section';
import { SkillList } from './skill-list';
import { StrengthList } from './strength-list';

export const metadata: Metadata = {
  title: 'Resumé Lukas Grimm',
};

export default async function Resume() {
  const resume = await loadJsonFile<Resume>('./data/resume.json').then((resume) => ({
    ...resume,
    experienceList: resume.experienceList.map((experience) => ({
      ...experience,
      startDate: new Date(experience.startDate),
      endDate: experience.endDate && new Date(experience.endDate),
    })),
    educationList: resume.educationList.map((education) => ({
      ...education,
      startDate: new Date(education.startDate),
      endDate: new Date(education.endDate),
    })),
  }));

  return (
    <main className="w-[400px] mx-4 grid grid-cols-1 grid-rows-[auto_min-content_min-content_auto] gap-4 grid-flow-dense mb-8 sm:mx-auto md:grid-cols-3 md:w-[800px]">
      <header className="mt-4 md:col-span-3">
        <h1 className="text-4xl font-bold text-center">
          Lukas Grimm
        </h1>
        <h2 className="text-2xl font-medium text-center">
          Software Engineer
        </h2>
      </header>
      <ResumeSection className="mt-2 md:col-span-1" title="Biography">
        <Biography biography={resume.biography} />
      </ResumeSection>
      <ResumeSection className="mt-2 md:col-span-2 md:col-start-2 md:row-span-3" title="Experience">
        <ExperienceList experienceList={resume.experienceList} />
      </ResumeSection>
      <ResumeSection className="mt-2 md:col-span-2 md:col-start-2" title="Education">
        <EducationList educationList={resume.educationList} />
      </ResumeSection>
      <ResumeSection className="mt-2 md:col-span-2 md:col-start-2" title="Skills">
        <SkillList skills={resume.skills} />
      </ResumeSection>
      <ResumeSection className="mt-2 md:col-span-1" title="Strengths">
        <StrengthList strengths={resume.strengths} />
      </ResumeSection>
    </main>
  );
};
